[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/intro-media"
  [headers.values]
    Content-Type = "video/mp4"
    Content-Disposition = "inline"
    Accept-Ranges = "bytes"
